name: Deploy to Render on Main Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Deploy on Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cvap8c56l47c73a6qubg?key=WS68l3TYCb8" \
               -H "Authorization: Bearer ${{ secrets.RENDER_API }}" \
               -H "Accept: application/json" \
               -H "Content-Type: application/json" \
               -d '{ "clearCache": false }'
